### ISSUE TITLE
Trying to download a large PAN image results in errors

### ISSUE THREAD

**Issue by nricklin** [DigitalGlobe/gbdxtools#126]
Running this script:
```python
from gbdxtools import CatalogImage
img = CatalogImage('104001001BA7C400', band_type='Pan')
import numpy as np
from gbdxtools.ipe.io import to_geotiff
aoi = img.aoi(bbox=[2.0889757156372075,47.030,2.601077842712403,51.999])

import time
print time.time()

tif = to_geotiff(aoi, path='paris_pan.tif', dtype=np.uint16, proj='EPSG:32631')
print time.time()
```

Results in:
```
1497971073.16
Fetching Image... 148129 tiles
Traceback (most recent call last):
  File "fulltif.py", line 11, in <module>
    tif = to_geotiff(aoi, path='paris_pan.tif', dtype=np.uint16, proj='EPSG:32631')
  File "/usr/local/lib/python2.7/dist-packages/gbdxtools/ipe/io.py", line 6, in to_geotiff
    data = arr.read()
  File "/usr/local/lib/python2.7/dist-packages/gbdxtools/images/ipe_image.py", line 102, in read
    arr = self.compute(get=threaded_get)
  File "/usr/local/lib/python2.7/dist-packages/dask/base.py", line 79, in compute
    return compute(self, **kwargs)[0]
  File "/usr/local/lib/python2.7/dist-packages/dask/base.py", line 184, in compute
    for a in args)
  File "/usr/local/lib/python2.7/dist-packages/dask/base.py", line 184, in <genexpr>
    for a in args)
  File "/usr/local/lib/python2.7/dist-packages/dask/array/core.py", line 890, in finalize
    return concatenate3(results)
  File "/usr/local/lib/python2.7/dist-packages/dask/array/core.py", line 3330, in concatenate3
    result[idx] = arr
ValueError: could not broadcast input array from shape (8,256,256) into shape (1,256,256)
```

**Comment by pramukta** [comment]
@chelm @nricklin: This particular error fixed in the radd-dev branch, though it may still not work since it might try and build up that image in memory, not 100% sure on that.  Related to #107.

**Comment by chelm** [comment]
@pramukta let's sync up on what commits or code i can PR into master to get around this.

**Comment by pramukta** [comment]
@chelm @nricklin While the error above is fixed, I'm sure there are others that prevent this script from running.  Unfortuately the first error is that this cat_id is no longer available.  I'm going to close this but we should open a new on with whatever new errors shot up with this script.
