### ISSUE TITLE
KeyError: 'numBands' when using trying to use CatalogImage

### ISSUE THREAD

**Issue by aman-tiwari** [DigitalGlobe/gbdxtools#129]
Getting this:
``` python
>>> from gbdxtools import CatalogImage
>>> img = CatalogImage('104001001BA7C400')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/a/miniconda3/envs/py3k/lib/python3.6/site-packages/gbdxtools/images/catalog_image.py", line 59, in __init__
    super(CatalogImage, self).__init__(self._ipe_graphs, cat_id, node=self._node_id, **kwargs)
  File "/home/a/miniconda3/envs/py3k/lib/python3.6/site-packages/gbdxtools/images/ipe_image.py", line 152, in __init__
    self._cfg = self._config_dask()
  File "/home/a/miniconda3/envs/py3k/lib/python3.6/site-packages/gbdxtools/images/ipe_image.py", line 226, in _config_dask
    nbands = meta['image']['numBands']
KeyError: 'numBands'
```

with version `0.11.10` of `gbdxtools` on `Ubuntu 16.04.2 LTS`

**Comment by chelm** [comment]
This has to do with image metadata not being correctly fetched. I am going to add some error handling around that today and see if we can surface any issues sooner so we can get the root cause of this before the KeyError is triggered

**Comment by ealpert1** [comment]
https://vector.geobigdata.io/insight-vector/api/index/query/vector-gbdx-alpha-catalog-v2*/items?count=1000&q=item_type:IDAHOImage AND attributes.catalogID:104001001BA7C400&left=-180&right=180&upper=90&lower=-90

Returns: 

...
"attributes": {
                "profileName": "dg_1b",
                "tilePartition": "0000",
                "acquisitionDate": "2016-05-02T11:16:01.560Z",
                "bucketName": "idaho-images",
                **"numBands_int": 8,**
...
Not sure where the problem is but it's not CatV2

**Comment by chelm** [comment]
@ealpert1 awesome thanks! Yeah this has to do with accessing idaho metadata from IPE. Which has typically occurred via auth issues in the past.

**Comment by chelm** [comment]
@aman-tiwari Can you let me know how you're authenticating in gbdxtools? ie are you using a `~/.gbdx-config` file?

**Comment by aman-tiwari** [comment]
yes, I'm using a `.gbdx-config` file
This works fine:
``` python
>>> from gbdxtools import Interface
>>> gbdx = Interface()
```

**Comment by chelm** [comment]
@aman-tiwari great! I'm curious to know what happens if you remove the `gbdx_token` section and everything below it, (and restart your notebook kernel), does the CatalogImage then instantiate cleanly?

**Comment by aman-tiwari** [comment]
nope, same error

**Comment by pramukta** [comment]
@chelm @aman-tiwari it's actually looks like some sort of race condition on ipe that nate mac and dan mccabe are aware of.  we would catch the error and report here but the http status code comes back as success with the error in the json body.  We'll try and figure out more and put in a check for the error if it's going to be a bit.

**Comment by chelm** [comment]
@aman-tiwari We've merge a PR that won't particularly fix the issue your having but should shed light on the underlying problem. Would you mind upgrading to `gbdxtools v0.11.13`? You should no longer see the `numbands` KeyError but rather a `BadRequest` exception with some error info. 

Would love to know what error you see.

**Comment by aman-tiwari** [comment]
i see this now:
```python
>>> from gbdxtools import CatalogImage
>>> img = CatalogImage('104001001BA7C400')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/a/miniconda3/envs/py3k/lib/python3.6/site-packages/gbdxtools/images/catalog_image.py", line 59, in __init__
    super(CatalogImage, self).__init__(self._ipe_graphs, cat_id, node=self._node_id, **kwargs)
  File "/home/a/miniconda3/envs/py3k/lib/python3.6/site-packages/gbdxtools/images/ipe_image.py", line 152, in __init__
    self._cfg = self._config_dask()
  File "/home/a/miniconda3/envs/py3k/lib/python3.6/site-packages/gbdxtools/images/ipe_image.py", line 228, in _config_dask
    meta = self.ipe_metadata
  File "/home/a/miniconda3/envs/py3k/lib/python3.6/site-packages/gbdxtools/images/ipe_image.py", line 178, in ipe_metadata
    self._ipe_metadata = get_ipe_metadata(self.interface.gbdx_connection, self.ipe_id, self.ipe_node_id)
  File "/home/a/miniconda3/envs/py3k/lib/python3.6/site-packages/gbdxtools/ipe/graph.py", line 31, in get_ipe_metadata
    meta['image'] = fetch_metadata(conn, VIRTUAL_IPE_URL + "/metadata/idaho-virtual/{}/{}/image.json".format(ipe_id, node)) 
  File "/home/a/miniconda3/envs/py3k/lib/python3.6/site-packages/gbdxtools/ipe/graph.py", line 25, in fetch_metadata
    raise BadRequest("Problem fetching image metadata: {}".format(res_json.get('error', res_json['message'])))
gbdxtools.ipe.error.BadRequest: Problem fetching image metadata: graph id b'eeeb9dac8fe5cad19edf20c44e070afe411e5655719e80bde1ac058ec9075686' does not exist
```

**Comment by chelm** [comment]
@aman-tiwari great! That gives me something to dig into! I'll dig in and see why this might be happening.

**Comment by chelm** [comment]
@aman-tiwari We're dug in a little to bit this issue and deployed a change to the backend API that might help your issue (i have yet to reproduce the issue locally so it has been hard for me to test fixes). 

I also have a small change to retry failed requests a number of times before erroring, but its not PR'd yet. 

Would mind giving it another spin for me?

**Comment by aman-tiwari** [comment]
same error, but with different graph ids each time:
```python
>>> from gbdxtools import CatalogImage
>>> img = CatalogImage('104001001BA7C400')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/a/miniconda3/envs/py3k/lib/python3.6/site-packages/gbdxtools/images/catalog_image.py", line 59, in __init__
    super(CatalogImage, self).__init__(self._ipe_graphs, cat_id, node=self._node_id, **kwargs)
  File "/home/a/miniconda3/envs/py3k/lib/python3.6/site-packages/gbdxtools/images/ipe_image.py", line 152, in __init__
    self._cfg = self._config_dask()
  File "/home/a/miniconda3/envs/py3k/lib/python3.6/site-packages/gbdxtools/images/ipe_image.py", line 228, in _config_dask
    meta = self.ipe_metadata
  File "/home/a/miniconda3/envs/py3k/lib/python3.6/site-packages/gbdxtools/images/ipe_image.py", line 178, in ipe_metadata
    self._ipe_metadata = get_ipe_metadata(self.interface.gbdx_connection, self.ipe_id, self.ipe_node_id)
  File "/home/a/miniconda3/envs/py3k/lib/python3.6/site-packages/gbdxtools/ipe/graph.py", line 31, in get_ipe_metadata
    meta['image'] = fetch_metadata(conn, VIRTUAL_IPE_URL + "/metadata/idaho-virtual/{}/{}/image.json".format(ipe_id, node)) 
  File "/home/a/miniconda3/envs/py3k/lib/python3.6/site-packages/gbdxtools/ipe/graph.py", line 25, in fetch_metadata
    raise BadRequest("Problem fetching image metadata: {}".format(res_json.get('error', res_json['message'])))
gbdxtools.ipe.error.BadRequest: Problem fetching image metadata: graph id b'eeeb9dac8fe5cad19edf20c44e070afe411e5655719e80bde1ac058ec9075686' does not exist
>>> 
>>> img = CatalogImage('104001001BA7C400')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/a/miniconda3/envs/py3k/lib/python3.6/site-packages/gbdxtools/images/catalog_image.py", line 59, in __init__
    super(CatalogImage, self).__init__(self._ipe_graphs, cat_id, node=self._node_id, **kwargs)
  File "/home/a/miniconda3/envs/py3k/lib/python3.6/site-packages/gbdxtools/images/ipe_image.py", line 152, in __init__
    self._cfg = self._config_dask()
  File "/home/a/miniconda3/envs/py3k/lib/python3.6/site-packages/gbdxtools/images/ipe_image.py", line 228, in _config_dask
    meta = self.ipe_metadata
  File "/home/a/miniconda3/envs/py3k/lib/python3.6/site-packages/gbdxtools/images/ipe_image.py", line 178, in ipe_metadata
    self._ipe_metadata = get_ipe_metadata(self.interface.gbdx_connection, self.ipe_id, self.ipe_node_id)
  File "/home/a/miniconda3/envs/py3k/lib/python3.6/site-packages/gbdxtools/ipe/graph.py", line 31, in get_ipe_metadata
    meta['image'] = fetch_metadata(conn, VIRTUAL_IPE_URL + "/metadata/idaho-virtual/{}/{}/image.json".format(ipe_id, node)) 
  File "/home/a/miniconda3/envs/py3k/lib/python3.6/site-packages/gbdxtools/ipe/graph.py", line 25, in fetch_metadata
    raise BadRequest("Problem fetching image metadata: {}".format(res_json.get('error', res_json['message'])))
gbdxtools.ipe.error.BadRequest: Problem fetching image metadata: graph id b'fa541797cd7450ce69c4e4d74eaccf58fb73169b4c874dd49044358d459b8905' does not exist
>>> img = CatalogImage('104001001BA7C400')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/a/miniconda3/envs/py3k/lib/python3.6/site-packages/gbdxtools/images/catalog_image.py", line 59, in __init__
    super(CatalogImage, self).__init__(self._ipe_graphs, cat_id, node=self._node_id, **kwargs)
  File "/home/a/miniconda3/envs/py3k/lib/python3.6/site-packages/gbdxtools/images/ipe_image.py", line 152, in __init__
    self._cfg = self._config_dask()
  File "/home/a/miniconda3/envs/py3k/lib/python3.6/site-packages/gbdxtools/images/ipe_image.py", line 228, in _config_dask
    meta = self.ipe_metadata
  File "/home/a/miniconda3/envs/py3k/lib/python3.6/site-packages/gbdxtools/images/ipe_image.py", line 178, in ipe_metadata
    self._ipe_metadata = get_ipe_metadata(self.interface.gbdx_connection, self.ipe_id, self.ipe_node_id)
  File "/home/a/miniconda3/envs/py3k/lib/python3.6/site-packages/gbdxtools/ipe/graph.py", line 31, in get_ipe_metadata
    meta['image'] = fetch_metadata(conn, VIRTUAL_IPE_URL + "/metadata/idaho-virtual/{}/{}/image.json".format(ipe_id, node)) 
  File "/home/a/miniconda3/envs/py3k/lib/python3.6/site-packages/gbdxtools/ipe/graph.py", line 25, in fetch_metadata
    raise BadRequest("Problem fetching image metadata: {}".format(res_json.get('error', res_json['message'])))
gbdxtools.ipe.error.BadRequest: Problem fetching image metadata: graph id b'eeeb9dac8fe5cad19edf20c44e070afe411e5655719e80bde1ac058ec9075686' does not exist
```

**Comment by chelm** [comment]
Thanks for trying it again. I'm really interested in getting this fixed. I saw a similar bug with the different graph ids and raised the issue so we'll get some insight into whats happening there. 

In the meantime i'll get the request retry solution worked up and we'll try again. We're thinking its a race with the graph generation that they're working on solving.

**Comment by pramukta** [comment]
@chelm @aman-tiwari I believe this is fixed, so will close out for now.  If you encounter this again def reopen.
