### ISSUE TITLE
pyproj install problem

### ISSUE THREAD

**Issue by robinkraft** [DigitalGlobe/gbdxtools#155]
I'm not able to install `gbdxtools` on my Mac using a fresh `conda` environment. It seems to be some issue with `pyproj`, as noted in https://github.com/jswhit/pyproj/issues/103 and https://github.com/ozak/georasters/issues/16. Anyone else seeing this?

```shell
gcc -fno-strict-aliasing -I/Users/robin/miniconda2/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Isrc -I/Users/robin/miniconda2/include/python2.7 -c src/pj_fwd3d.c -o build/temp.macosx-10.7-x86_64-2.7/src/pj_fwd3d.o
    src/pj_fwd3d.c:6:2: error: unknown type name 'XYZ'; did you mean 'XY'?
            XYZ /* forward projection entry */
            ^~~
            XY
    /Users/robin/miniconda2/include/projects.h:155:37: note: 'XY' declared here
    typedef struct { double x, y; }     XY;
                                        ^
    src/pj_fwd3d.c:7:10: error: unknown type name 'LPZ'; did you mean 'LP'?
    pj_fwd3d(LPZ lpz, PJ *P) {
             ^~~
             LP
    /Users/robin/miniconda2/include/projects.h:156:37: note: 'LP' declared here
    typedef struct { double lam, phi; } LP;
                                        ^
    src/pj_fwd3d.c:8:2: error: unknown type name 'XYZ'; did you mean 'XY'?
            XYZ xyz;
            ^~~
            XY
    /Users/robin/miniconda2/include/projects.h:155:37: note: 'XY' declared here
    typedef struct { double x, y; }     XY;
                                        ^
    src/pj_fwd3d.c:13:23: error: no member named 'z' in 'XY'
                    xyz.x = xyz.y = xyz.z = HUGE_VAL;
                                    ~~~ ^
    src/pj_fwd3d.c:29:24: error: no member named 'fwd3d' in 'struct PJconsts'
                    if (P->fwd3d != NULL)
                        ~  ^
    src/pj_fwd3d.c:31:18: error: no member named 'fwd3d' in 'struct PJconsts'
                        xyz = (*P->fwd3d)(lpz, P); /* project */
                                ~  ^
    src/pj_fwd3d.c:33:24: error: no member named 'z' in 'XY'
                            xyz.x = xyz.y = xyz.z = HUGE_VAL;
                                            ~~~ ^
    src/pj_fwd3d.c:43:41: error: no member named 'z' in 'XY'
                        xyz.x = xyz.y = xyz.z = HUGE_VAL;
                                        ~~~ ^
    8 errors generated.
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/Users/robin/miniconda2/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/8r/rlfbfb1s221g1bh2msjcxlw80000gn/T/pip-build-WLK59U/pyproj/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/8r/rlfbfb1s221g1bh2msjcxlw80000gn/T/pip-OGAgbk-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/8r/rlfbfb1s221g1bh2msjcxlw80000gn/T/pip-build-WLK59U/pyproj/
```

**Comment by pramukta** [comment]
Hi @robinkraft, could you try installing it in your conda environment using the command `conda install -c digitalglobe gbdxtools` (assuming it's a py27 environment).  We're still trying to figure out why the package doesn't think it matches py3.x but it should get around the pyproj issue.  Alternatively you might install pyproj via conda before using pip to instal gbdxtools.

**Comment by robinkraft** [comment]
Thanks @pramukta. I'm getting this error now (using your suggested `install -c` method):

```shell
conda install -c digitalglobe gbdxtools
Fetching package metadata ...........
Solving package specifications:


PackageNotFoundError: Dependencies missing in current osx-64 channels:
  - gbdxtools -> gbdx-auth ==0.2.4 -> pyjwt ==1.4.2
  - gbdxtools -> pygeoif ==0.6

Close matches found; did you mean one of these?

    pygeoif: geotiff

(and similarly for the other packages)
```

**Comment by robinkraft** [comment]
Ok, FWIW I got things installed using the following incantation:

```shell
conda create -n gbdxenv
source activate gbdxenv
conda install pyproj
pip install gbdxtools
conda install pycurl  # workaround for libcurl version issue
python
>>> import gbdxtools
>>>
```

**Comment by robinkraft** [comment]
As a followup, I neglected to mention that my initial attempt was actually using `pip install gbdxtools` in a `conda` virtual environment. Not trying to install directly with `conda`.

Also, I just tried redoing the install that same way using the most recent update and a completely fresh `conda` install, and there was no problem with `pyproj`. However, `libcurl` had a version issue when I tried `import gbdxtools`:

```shell
>>> import gbdxtools
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/robin/miniconda2/lib/python2.7/site-packages/gbdxtools/__init__.py", line 3, in <module>
    from gbdxtools.images.idaho_image import IdahoImage
  File "/Users/robin/miniconda2/lib/python2.7/site-packages/gbdxtools/images/idaho_image.py", line 5, in <module>
    from gbdxtools.ipe.interface import Ipe
  File "/Users/robin/miniconda2/lib/python2.7/site-packages/gbdxtools/ipe/interface.py", line 15, in <module>
    import pycurl
ImportError: dlopen(/Users/robin/miniconda2/lib/python2.7/site-packages/pycurl.so, 2): Library not loaded: @rpath/libcurl.4.dylib
  Referenced from: /Users/robin/miniconda2/lib/python2.7/site-packages/pycurl.so
  Reason: Incompatible library version: pycurl.so requires version 9.0.0 or later, but libcurl.4.dylib provides version 7.0.0
```
My workaround was `conda install pycurl` as above. Just wanted to let you know that `pyproj` isn't an issue anymore. Woohoo!

**Comment by pramukta** [comment]
Ah ok, @robinkraft I think you'll encounter trouble with conda right now, I'm attempting to get a build up there that works with python3 as well and had to temporarily take down the existing package (folks on windows using tensorflow are in particular need of it). Will post an update here when I have that up, should be in the next hour or so.  Sorry about that.

**Comment by pramukta** [comment]
Okay there is a build up there that should install smoothly in 2.7 and 3.5.  For 3.5, you'll need to make sure that libtiff >=4.0.6-2 gets installed (rather than 4.0.6-1 because of this: https://github.com/ContinuumIO/anaconda-issues/issues/25).  Ive seen happen automatically unless python 3.5.0 comes down (rather than a more recent one like 3.5.4).  If you end up wanting to update to 0.13.4 (assuming you don't have that) and things break for you def open another ticket and we'll take a look.  In the mean time will close this out.
