### ISSUE TITLE
Memory error while trying to download Pan Image

### ISSUE THREAD

**Issue by nricklin** [DigitalGlobe/gbdxtools#178]
I'm running this code on a m4.4xlarge instance (64G RAM) to try to materialize a full Pan image:
```python
import time
catid = '1030010009A84E00' # multipart WV02 strip over Boulder
from gbdxtools import CatalogImage
img = CatalogImage(catid, band_type='Pan')
import numpy as np
from gbdxtools.ipe.io import to_geotiff
start = time.time()
tif = to_geotiff(img, path='pan_image.tif', dtype=np.uint16, proj='EPSG:32631')
duration = time.time() - start
print duration
```
After about 2 hours, I get this error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/gbdxtools/ipe/io.py", line 8, in to_geotiff
    data = arr.read(bands=bands)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/gbdxtools/images/meta.py", line 112, in wrapped
    result = fn(*args, **kwargs)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/gbdxtools/images/ipe_image.py", line 92, in read
    return super(IpeImage, self).read(bands=bands)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/gbdxtools/images/meta.py", line 144, in read
    return arr.compute(num_workers=num_workers)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/gbdxtools/images/meta.py", line 112, in wrapped
    result = fn(*args, **kwargs)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/dask/base.py", line 99, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/dask/base.py", line 211, in compute
    for a in args)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/dask/base.py", line 211, in <genexpr>
    for a in args)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/dask/array/core.py", line 939, in finalize
    return concatenate3(results)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/dask/array/core.py", line 2881, in concatenate3
    result = np.empty(shape=shape, dtype=dtype(deepfirst(arrays)))
MemoryError
>>> duration = time.time() - start
>>> print duration
6914.04080105
```

**Comment by chelm** [comment]
@nricklin "cool" find - do you know how big the PAN image is in total, in GB? im not surprised we run into Mem issues with massive (>20gb?) numpy arrays.

I wonder if instead of trying pull the entire array into memory we could get smarter about how we write Geotiffs. There very could be a cleaner way to write chunks via rasterio (since it has probably already dealt with this)

**Comment by chelm** [comment]
i was able to create a really big tiff on the same ec2 instance using windowed writes for the tif. See: https://github.com/DigitalGlobe/gbdxtools/commit/93b0b9953358f2e7ab21f8c7454189115664eae7

**Comment by chelm** [comment]
I was able to implement a concurrent write solution that materialzed the entire image in to 43gb tif. Took 10 hours, but i think it should have only taken 2. This leads me to believe that the GIL might not be getting freed up correctly but im not sure.
