### ISSUE TITLE
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url

### ISSUE THREAD

**Issue by aman-tiwari** [DigitalGlobe/gbdxtools#228]
When ordering certain IDs, I get a `requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://geobigdata.io/orders/v2/order` error.

I'm using gbdxtools 0.14.4.

Here is the code and traceback:
```python
import traceback
gbdx = gbdxtools.Interface()
order_ids = []
for id in need_to_order:
    print("trying to order ", id)
    try:
        order_ids.append(gbdx.ordering.order(id))
    except Exception as e:
        traceback.print_exc()
        print(type(e), " for " + id, e)
        pass
    print(order_ids[-1])
```

and 

```python
trying to order  103001003E3F0C00
e5909758-1564-40f8-939a-cbedb1bb0fae
trying to order  103001003B7A5400
88cf56f3-8c66-4166-a68d-21ec78e4a95a
trying to order  1030010029C6EF00

Traceback (most recent call last):
  File "<ipython-input-41-f967fd4fc914>", line 7, in <module>
    order_ids.append(gbdx.ordering.order(id))
  File "/home/studio/miniconda3/envs/py3k/lib/python3.6/site-packages/gbdxtools/ordering.py", line 71, in order
    _order_single_batch(url, sanitized_ids[-remain_count:], res)
  File "/home/studio/miniconda3/envs/py3k/lib/python3.6/site-packages/gbdxtools/ordering.py", line 47, in _order_single_batch
    r.raise_for_status()
  File "/home/studio/miniconda3/envs/py3k/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://geobigdata.io/orders/v2/order

<class 'requests.exceptions.HTTPError'>  for 1030010029C6EF00 403 Client Error: Forbidden for url: https://geobigdata.io/orders/v2/order
88cf56f3-8c66-4166-a68d-21ec78e4a95a
trying to order  103001002B548600

Traceback (most recent call last):
  File "<ipython-input-41-f967fd4fc914>", line 7, in <module>
    order_ids.append(gbdx.ordering.order(id))
  File "/home/studio/miniconda3/envs/py3k/lib/python3.6/site-packages/gbdxtools/ordering.py", line 71, in order
    _order_single_batch(url, sanitized_ids[-remain_count:], res)
  File "/home/studio/miniconda3/envs/py3k/lib/python3.6/site-packages/gbdxtools/ordering.py", line 47, in _order_single_batch
    r.raise_for_status()
  File "/home/studio/miniconda3/envs/py3k/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://geobigdata.io/orders/v2/order

<class 'requests.exceptions.HTTPError'>  for 103001002B548600 403 Client Error: Forbidden for url: https://geobigdata.io/orders/v2/order
88cf56f3-8c66-4166-a68d-21ec78e4a95a
trying to order  103001002CCED900

Traceback (most recent call last):
  File "<ipython-input-41-f967fd4fc914>", line 7, in <module>
    order_ids.append(gbdx.ordering.order(id))
  File "/home/studio/miniconda3/envs/py3k/lib/python3.6/site-packages/gbdxtools/ordering.py", line 71, in order
    _order_single_batch(url, sanitized_ids[-remain_count:], res)
  File "/home/studio/miniconda3/envs/py3k/lib/python3.6/site-packages/gbdxtools/ordering.py", line 47, in _order_single_batch
    r.raise_for_status()
  File "/home/studio/miniconda3/envs/py3k/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://geobigdata.io/orders/v2/order

<class 'requests.exceptions.HTTPError'>  for 103001002CCED900 403 Client Error: Forbidden for url: https://geobigdata.io/orders/v2/order
88cf56f3-8c66-4166-a68d-21ec78e4a95a
trying to order  103001002B777200

Traceback (most recent call last):
  File "<ipython-input-41-f967fd4fc914>", line 7, in <module>
    order_ids.append(gbdx.ordering.order(id))
  File "/home/studio/miniconda3/envs/py3k/lib/python3.6/site-packages/gbdxtools/ordering.py", line 71, in order
    _order_single_batch(url, sanitized_ids[-remain_count:], res)
  File "/home/studio/miniconda3/envs/py3k/lib/python3.6/site-packages/gbdxtools/ordering.py", line 47, in _order_single_batch
    r.raise_for_status()
  File "/home/studio/miniconda3/envs/py3k/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://geobigdata.io/orders/v2/order

<class 'requests.exceptions.HTTPError'>  for 103001002B777200 403 Client Error: Forbidden for url: https://geobigdata.io/orders/v2/order
88cf56f3-8c66-4166-a68d-21ec78e4a95a
trying to order  10300100272F9300

Traceback (most recent call last):
  File "<ipython-input-41-f967fd4fc914>", line 7, in <module>
    order_ids.append(gbdx.ordering.order(id))
  File "/home/studio/miniconda3/envs/py3k/lib/python3.6/site-packages/gbdxtools/ordering.py", line 71, in order
    _order_single_batch(url, sanitized_ids[-remain_count:], res)
  File "/home/studio/miniconda3/envs/py3k/lib/python3.6/site-packages/gbdxtools/ordering.py", line 47, in _order_single_batch
    r.raise_for_status()
  File "/home/studio/miniconda3/envs/py3k/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://geobigdata.io/orders/v2/order

<class 'requests.exceptions.HTTPError'>  for 10300100272F9300 403 Client Error: Forbidden for url: https://geobigdata.io/orders/v2/order
88cf56f3-8c66-4166-a68d-21ec78e4a95a
trying to order  10300100224E1000
<class 'requests.exceptions.HTTPError'>  for 10300100224E1000 403 Client Error: Forbidden for url: https://geobigdata.io/orders/v2/order
88cf56f3-8c66-4166-a68d-21ec78e4a95a
trying to order  103001001FB56500
301281df-732c-4aea-8cb8-2e2754cc4c98

Traceback (most recent call last):
  File "<ipython-input-41-f967fd4fc914>", line 7, in <module>
    order_ids.append(gbdx.ordering.order(id))
  File "/home/studio/miniconda3/envs/py3k/lib/python3.6/site-packages/gbdxtools/ordering.py", line 71, in order
    _order_single_batch(url, sanitized_ids[-remain_count:], res)
  File "/home/studio/miniconda3/envs/py3k/lib/python3.6/site-packages/gbdxtools/ordering.py", line 47, in _order_single_batch
    r.raise_for_status()
  File "/home/studio/miniconda3/envs/py3k/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://geobigdata.io/orders/v2/order
```

**Comment by chelm** [comment]
@aman-tiwari Does this only happen with certain IDs? Or every ID you try to order?

**Comment by aman-tiwari** [comment]
It only happens with certain IDs, e.g in the traceback there is an error for `10300100272F9300` but not for `103001003E3F0C00`

**Comment by chelm** [comment]
@aman-tiwari Can you share each of the catalog ids in `need_to_order`? That might help me look for differences. I'll need to reach out and check why you'd be able to order some images and not others.

**Comment by chelm** [comment]
@aman-tiwari You may be hitting limits on ordering, I'll check more into that on Monday.

**Comment by chelm** [comment]
@aman-tiwari Are you still running into this issue?

**Comment by aman-tiwari** [comment]
Hey @chelm , I am still experiencing it

**Comment by chelm** [comment]
I've been told that eval tier users can order 20 images before they need to upgrade. I'll confirm that but i think that's whats going on here. You've hit the limit.

**Comment by chelm** [comment]
Confirmed that your GBDX Account hit the limit of number images you can order.
